[workspace]
members = ["crates/*"]
resolver = "2"
# Exclude xtask so there is only one binary (aoc), meaning it doesn't have to be specified when using cargo run
default-members = ["crates/aoc", "crates/utils", "crates/year*"]

[workspace.package]
authors = ["Ethan Jones <ictrobot@outlook.com>"]
edition = "2024"
license = "MIT"
publish = false
repository = "https://github.com/ictrobot/aoc-rs"
rust-version = "1.99"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
allow_attributes = "deny"
dbg_macro = "warn"
large_stack_arrays = "allow"
many_single_char_names = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
module_name_repetitions = "allow"
naive_bytecount = "allow"
needless_bitwise_bool = "allow"
print_stderr = "warn"
print_stdout = "warn"
similar_names = "allow"
too_many_lines = "allow"

[profile.release]
debug = "limited"
