[package]
name = "year2015"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }

[dependencies]
utils = { path = "../utils" }
